# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58d99b925530ecd6d02849976df9d26d2e0d7467f6860808cc820f563cf27f5b43dc721f1776f44af2c288f98975e0afc3b03bb37165bdc51ef6cedf945f3c83

test:
  secret_key_base: 61ca3d0ea6bd2d0ec4fd2f5f6108688b1a471abab067270981460a60ef3996f130670db764b6fd2b4e83396780151148624c9b6b255f8e42561d1c79b369463e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
